CREATE TABLE IF NOT EXISTS item_category (
    id INT auto_increment PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_category_id INT DEFAULT 1,
    active TINYINT DEFAULT 1
);